green:
  enabled: @enable-green@
  image: nginxinc/nginx-unprivileged
  version: 1.19.2

productionSlot: @slot-color@

replicaCount: 1

ingress:
  stagehostname: @hostname-green@.apps.mcm-ocp4.ocpdns.local

index: hello world
index_green: travel planner v3 - nginx 1.19.2 - green slot
